### ISSUE TITLE
JLibra 업데이트 이슈

### ISSUE THREAD

**Issue by forfido** [forfido/libra-wallet#13]
Mint 및 Send libra 가 blockchain망에서 허용처리 안되고 있음

**Comment by bigone-k** [comment]
Plan B 감안하여 미리 작업 진행 하겠음.

**Comment by bigone-k** [comment]
BackEnd 작성 한후 주석 처리 할 예정

**Comment by forfido** [comment]
* 0.7.0 인터페이스에 맞게 수정 완료  
* Getbalance, Mint, Transfer 모두 JLibra로 정상 동작됨
