### ISSUE TITLE
EndPoint 에러 이슈

### ISSUE THREAD

**Issue by bigone-k** [forfido/libra-wallet#17]
> http://wallet-api.palibra.net/user/search/email/{keyword}

- ex ) 
http://wallet-api.palibra.net/user/search/email/y

_500 에러 발생_

"message": "For queries with named parameters you need to use provide names for method parameters. Use @Param for query method parameters, or when on Java 8+ use the javac flag -parameters.; nested exception is java.lang.IllegalStateException: For queries with named parameters you need to use provide names for method parameters. Use @Param for query method parameters, or when on Java 8+ use the javac flag -parameters.",

**Comment by bigone-k** [comment]
`open jdk > java 1.8 변경 필요 `

**Comment by forfido** [comment]
java 버젼 문제가 아니었음  
JPQL 관련 이슈사항으로 아래와 같이 파라미터에 @Param 을 명시하는 것으로 해결

  `  List<UserDto> searchEmailsByKeyword(@Param("keyword") String keyword);`

https://www.logicbig.com/tutorials/spring-framework/spring-data/query-named-parameters.html

**Comment by forfido** [comment]
현재 aws ec2 서버의 자바 버젼은 openjdk 8 -> java 1.8.0 으로 변경은 했음
