### ISSUE TITLE
세션 상관 없이 항상 /Home을 바라 보는 문제

### ISSUE THREAD

**Issue by forfido** [forfido/libra-wallet#6]
로그아웃을 해도 /Home 에 고정되는 현상.

현재 작업 중인 부분이 Oauth2로 구글로그인 후 Redirect 페이지로 세션 만들기 하고 있음.
그런데 항상 /Home 밖에 라우팅 되지 않는 문제로 진행이 안됨....

**Comment by bigone-k** [comment]
```vue
// Create a new router
const router = new Router({
  mode: "history",
  routes: paths
    .map(path => route(path.path, path.view, path.name))
    .concat([{ path: "*", redirect: "/Home" }]),

  scrollBehavior(to, from, savedPosition) {
    if (savedPosition) {
      return savedPosition;
    }
    if (to.hash) {
      return { selector: to.hash };
    }
    return { x: 0, y: 0 };
  }

});
```


router/index.js 에서 
패스가 지정 되지 않는 경우 home으로 리다렉션하고 있습니다.
혹시 구글 로그인 시 어느 path로 리다렉션 되는지 알 수 있을가요?
```js
.concat([{ path: "*", redirect: "/Home" }]),
```

**Comment by forfido** [comment]
방금 푸시 했음, 
구글 로그인 URL은 다음과 같음 
http://localhost:8090/oauth2/authorize/google?redirect_uri=http://localhost:3000/Redirect

**Comment by bigone-k** [comment]
## Issue  해결 되었습니다. 

*이슈해결설명*
- 첫번째 axios 생성 시 header가 없는 상태로 new를 하게 됨, 
- 정상적인 인증 이후, router를 통해 Home 페이지로 redirect로 가는 도 중 routerguide부분에서 걸림.

_rest 통신 401 에러  ( 인증 에러 )_

인증 이 전에 header 설정하는 것으로 변경  

> 추후 작업 이슈 ( axios Vue Instance 작업 할 예정)


close 하겠습니다.
